### ISSUE TITLE
Some data format issues

### ISSUE THREAD

**Issue by tianjiaoding** [torrvision/CollaborativeSLAMDataset#1]
Hi there,

Firstly, good work! I am interested in using your dataset in my research. However, after downloading and playing with the dataset for a while, I found it difficult to extract some camera parameters. I would appreciate it if you could instruct me a little bit.

Q1: Where can I find the camera calibration matrix K (or intrinsics)? I checked the "calib.txt" and could not find it. The third block seems to be some calibration between a stereo camera rig while I can not understand the first two blocks...

"calib.txt"

```
480 270
370.044 369.501
241.249 134.663

224 172
215.965 215.965
111.453 85.0044

0.999952 -0.009273 0.00302 0.000992
0.009273 0.999957 -0.000258 -0.011901
-0.003018 0.000286 0.999995 0.002581

affine 0.001 0
``` 

Q2:
In "frame-xxxx-pose.txt", is it true that the 4*4 transformation matrix takes as input a point in camera coordinate system and transform it into a point in world coordinate system, or is it the other way around? 

"frame-xxxx-pose.txt"
```
-0.733823 -0.13459 0.665874 -0.354835
0.0155285 0.976599 0.214508 -0.211572
-0.679163 0.167751 -0.714561 0.049265
0 -0 -0 1

```

Many thanks in advance.

Best Regards

**Comment by sgolodetz** [comment]
Thanks :) Glad you're interested in using it! For Q1, the first two sets of numbers are the intrinsics for the RGB and then depth cameras, in the form:

Image Width, Image Height
fx, fy
px, py

You can get the calibration matrix K by putting the focal lengths and principal point into a matrix thus:

fx 0 px
0 fy py
0 0 1

**Comment by sgolodetz** [comment]
For Q2, it's World space to Camera space. See also here:

https://github.com/torrvision/spaint/blob/master/modules/itmx/src/util/CameraPoseConverter.cpp

**Comment by sgolodetz** [comment]
For reference, the third block is the transformation between the RGB and depth cameras.

**Comment by sgolodetz** [comment]
See also here: https://github.com/victorprad/InfiniTAM/blob/master/InfiniTAM/ITMLib/Objects/Camera/ITMCalibIO.cpp
