### ISSUE TITLE
the download-big.sh download links failed

### ISSUE THREAD

**Issue by WZG3661** [torrvision/CollaborativeSLAMDataset#4]
The downloaded files cannot be decompressed

**Comment by sgolodetz** [comment]
The original server is no longer operating. I’ve re-uploaded the normal files but not yet the big ones to AWS (they were less readily accessible my end). It’s something I need to fix - sorry. Do you need them urgently, or is it mainly for curiosity? (I can prioritise it higher or lower based on that.)

**Comment by WZG3661** [comment]
I think your dataset meets my needs very well. It would be best if you could restore the download link as soon as possible. Thanks a lot!

**Comment by sgolodetz** [comment]
Ok no probs - I’ll look into it this week.

**Comment by WZG3661** [comment]
Thanks! Another question, I want to know the accuracy of your truth value? Centimeter scale？

**Comment by sgolodetz** [comment]
The camera poses come from visual-inertial tracking on an Asus ZenFone AR, so the accuracy is whatever that can deliver. It's pretty good, although not infallible. We didn't have a ground-truth LiDAR scan against which to compare, unfortunately, so it's hard to give a precise answer to the question. We did measure certain distances in the model using a laser range finder, as shown in the paper.

**Comment by sgolodetz** [comment]
I haven't had a chance to re-upload the big sequences yet, sorry - I need to find out the hard disk that has them on, and I'm not sure which one it is. I'll look into it as soon as I can.

**Comment by sgolodetz** [comment]
@WZG3661 Ok, finished recreating the full-size image sequences. Hope it all works ok now!
