### ISSUE TITLE
Why are there some strange colored patterns on the image?

### ISSUE THREAD

**Issue by wangziguo-nreal** [torrvision/CollaborativeSLAMDataset#5]
[https://img1.imgtp.com/2022/11/23/i6ODsJns.png](url)
on the upleft of this image:
[https://img1.imgtp.com/2022/11/23/t7PO1tOk.png](url)
I'm not sure you can see the image, I hope you can understand what I mean

**Comment by sgolodetz** [comment]
I seem to remember it being a saturation issue possibly, but it’s been a few years back.

@tcavallari Do you remember where we were on this one by any chance?

**Comment by tcavallari** [comment]
Yes, I remember those artifacts, saturation issue most likely, but I don't recall why we got them. Might have been a bug in the capture app that we fixed in the later scenes though, but I can't be sure. Too much time has passed, sorry.

**Comment by sgolodetz** [comment]
Ok thanks!

@wangziguo-nreal Practically, I seem to remember the artifacts being a few specific colours that you might be able to trivially filter out - that’s probably the simplest quick fix.

**Comment by wangziguo-nreal** [comment]
OK, thanks! I will try to filter it out
